import React from "react";
import { paperlogy } from "../../public/fonts/local_fonts";
import { PresenceProvider } from "@/contexts/PresenceContext";
import { UserInitializer } from "@/components/auth/UserInitializer";
import "../css/globals.css";
import { ToasterClient } from "@/components/common/ToasterClient";

export const metadata = {
  title: "DevCourse3",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning className="text-[14px] lg:text-[16px]">
      <body className={paperlogy.className}>
        {/* 실시간 접속자 관리를 위한 Provider */}
        <PresenceProvider channelName="dashboard">
          {/* 사용자 정보 초기화 Loader*/}
          <UserInitializer />
          <div className="min-h-screen bg-[#f9fafb] dark:bg-[#182236]">{children}</div>
        </PresenceProvider>
        <ToasterClient />
      </body>
    </html>
  );
}
